package icu.nd4y.dosette.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Seed: teal #00696B. Tonal values match design/mockups.
internal val LightColors =
    lightColorScheme(
        primary = Color(0xFF00696B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF9BF0F2),
        onPrimaryContainer = Color(0xFF002021),
        inversePrimary = Color(0xFF80D4D6),
        secondary = Color(0xFF486363),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCBE8E8),
        onSecondaryContainer = Color(0xFF041F20),
        tertiary = Color(0xFF8B5000),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCC0),
        onTertiaryContainer = Color(0xFF2C1600),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF6FAFA),
        onBackground = Color(0xFF161D1D),
        surface = Color(0xFFF6FAFA),
        onSurface = Color(0xFF161D1D),
        surfaceVariant = Color(0xFFDAE5E4),
        onSurfaceVariant = Color(0xFF3F4948),
        surfaceTint = Color(0xFF00696B),
        inverseSurface = Color(0xFF2B3232),
        inverseOnSurface = Color(0xFFEDF2F1),
        outline = Color(0xFF6F7979),
        outlineVariant = Color(0xFFBEC8C8),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF6FAFA),
        surfaceDim = Color(0xFFD6DBDB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF0F5F4),
        surfaceContainer = Color(0xFFE9EFEF),
        surfaceContainerHigh = Color(0xFFE3E9E9),
        surfaceContainerHighest = Color(0xFFDDE4E4),
    )

internal val DarkColors =
    darkColorScheme(
        primary = Color(0xFF80D4D6),
        onPrimary = Color(0xFF003739),
        primaryContainer = Color(0xFF004F52),
        onPrimaryContainer = Color(0xFF9BF0F2),
        inversePrimary = Color(0xFF00696B),
        secondary = Color(0xFFB0CCCC),
        onSecondary = Color(0xFF1B3435),
        secondaryContainer = Color(0xFF324B4C),
        onSecondaryContainer = Color(0xFFCBE8E8),
        tertiary = Color(0xFFFFB877),
        onTertiary = Color(0xFF4A2800),
        tertiaryContainer = Color(0xFF6A3C00),
        onTertiaryContainer = Color(0xFFFFDCC0),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF0E1415),
        onBackground = Color(0xFFDDE4E4),
        surface = Color(0xFF0E1415),
        onSurface = Color(0xFFDDE4E4),
        surfaceVariant = Color(0xFF3F4948),
        onSurfaceVariant = Color(0xFFBEC8C8),
        surfaceTint = Color(0xFF80D4D6),
        inverseSurface = Color(0xFFDDE4E4),
        inverseOnSurface = Color(0xFF2B3232),
        outline = Color(0xFF889392),
        outlineVariant = Color(0xFF3F4948),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF343A3A),
        surfaceDim = Color(0xFF0E1415),
        surfaceContainerLowest = Color(0xFF090F10),
        surfaceContainerLow = Color(0xFF161D1D),
        surfaceContainer = Color(0xFF1A2121),
        surfaceContainerHigh = Color(0xFF252B2B),
        surfaceContainerHighest = Color(0xFF303636),
    )
