style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

complexity:
  LongMethod:
    ignoreAnnotated: ['Composable']
  LongParameterList:
    ignoreAnnotated: ['Composable']
    ignoreDataClasses: true
    excludes: ['**/test/**', '**/androidTest/**']
  TooManyFunctions:
    thresholdInFiles: 40
    thresholdInClasses: 25
    thresholdInInterfaces: 25
